version: "3"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  uwsgi:
    expose:
      - "8000"
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_template
      POSTGRES_HOST: postgres
  nginx:
    ports:
      - 80:80
    build: ./nginx
    depends_on :
      - uwsgi